import mysql.connector as sql
from modules.creds import user_pwd
from cv_schema_init import *

mycon = sql.connect(host='localhost', user='root', passwd=user_pwd)
cur = mycon.cursor()
cur.execute(CREATE_SCHEMA)
cur.execute(Create_users_Table)
cur.execute(Create_recruiter_Table)
cur.execute(Create_client_Table)
cur.execute(Create_Job_Table)
cur.execute(Create_Application_Table)
cur.execute(Create_DELJOB_Table)
cur.execute(Create_DELAPP_Table)
cur.execute(Create_NEWJOB_Table)
cur.execute(Create_NEWAPP_Table)
cur.execute(f'USE mydb')
mycon.commit()
cur.execute(CREATE_Admin)
mycon.commit()
cur.execute(JobTrig1)
mycon.commit()
cur.execute(JobTrig2)
mycon.commit()
cur.execute(AppTrig)
mycon.commit()
cur.execute(totalAPP)
mycon.commit()
cur.execute(totalJOB)
mycon.commit()
cur.execute(totalUSERS)
mycon.commit()
cur.execute(Log_View)
mycon.commit()
mycon.close()